// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlcgen

type OperationOutput struct {
	WorkflowUuid    string
	FunctionID      int32
	FunctionName    string
	Output          *string
	Error           *string
	ChildWorkflowID *string
}

type WorkflowStatus struct {
	WorkflowUuid            string
	Status                  *string
	Name                    *string
	AuthenticatedUser       *string
	AssumedRole             *string
	AuthenticatedRoles      *string
	Request                 *string
	Output                  *string
	Error                   *string
	ExecutorID              *string
	CreatedAt               int64
	UpdatedAt               int64
	ApplicationVersion      *string
	ApplicationID           *string
	ClassName               *string
	ConfigName              *string
	RecoveryAttempts        *int64
	QueueName               *string
	WorkflowTimeoutMs       *int64
	WorkflowDeadlineEpochMs *int64
	Inputs                  *string
	StartedAtEpochMs        *int64
	DeduplicationID         *string
	Priority                int32
}
