// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlcgen

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type ApplicationVersion struct {
	VersionID        string
	VersionName      string
	VersionTimestamp int64
	CreatedAt        int64
}

type EventDispatchKv struct {
	ServiceName    string
	WorkflowFnName string
	Key            string
	Value          *string
	UpdateSeq      pgtype.Numeric
	UpdateTime     pgtype.Numeric
}

type Notification struct {
	DestinationUuid  string
	Topic            *string
	Message          string
	CreatedAtEpochMs int64
	MessageUuid      string
	Serialization    *string
	Consumed         bool
}

type OperationOutput struct {
	WorkflowUuid       string
	FunctionID         int32
	FunctionName       string
	Output             *string
	Error              *string
	ChildWorkflowID    *string
	StartedAtEpochMs   *int64
	CompletedAtEpochMs *int64
	Serialization      *string
}

type Stream struct {
	WorkflowUuid  string
	Key           string
	Value         string
	Offset        int32
	FunctionID    int32
	Serialization *string
}

type WorkflowEvent struct {
	WorkflowUuid  string
	Key           string
	Value         string
	Serialization *string
}

type WorkflowEventsHistory struct {
	WorkflowUuid  string
	FunctionID    int32
	Key           string
	Value         string
	Serialization *string
}

type WorkflowSchedule struct {
	ScheduleID        string
	ScheduleName      string
	WorkflowName      string
	WorkflowClassName *string
	Schedule          string
	Status            string
	Context           string
	LastFiredAt       *string
	AutomaticBackfill bool
	CronTimezone      *string
	QueueName         *string
}

type WorkflowStatus struct {
	WorkflowUuid            string
	Status                  *string
	Name                    *string
	AuthenticatedUser       *string
	AssumedRole             *string
	AuthenticatedRoles      *string
	Request                 *string
	Output                  *string
	Error                   *string
	ExecutorID              *string
	CreatedAt               int64
	UpdatedAt               int64
	ApplicationVersion      *string
	ApplicationID           *string
	ClassName               *string
	ConfigName              *string
	RecoveryAttempts        *int64
	QueueName               *string
	WorkflowTimeoutMs       *int64
	WorkflowDeadlineEpochMs *int64
	Inputs                  *string
	StartedAtEpochMs        *int64
	DeduplicationID         *string
	Priority                int32
	QueuePartitionKey       *string
	ForkedFrom              *string
	OwnerXid                *string
	ParentWorkflowID        *string
	Serialization           *string
	DelayUntilEpochMs       *int64
}
