// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package sqlcgen

import (
	"context"
)

const appendStreamEntry = `-- name: AppendStreamEntry :exec
INSERT INTO streams (workflow_uuid, key, value, "offset", function_id, serialization)
SELECT $1, $2, $3, COALESCE(
    (SELECT MAX("offset") FROM streams WHERE workflow_uuid = $1 AND key = $2), -1
) + 1, $4, $5
`

type AppendStreamEntryParams struct {
	WorkflowUuid  string
	Key           string
	Value         string
	FunctionID    int32
	Serialization *string
}

func (q *Queries) AppendStreamEntry(ctx context.Context, arg AppendStreamEntryParams) error {
	_, err := q.db.Exec(ctx, appendStreamEntry,
		arg.WorkflowUuid,
		arg.Key,
		arg.Value,
		arg.FunctionID,
		arg.Serialization,
	)
	return err
}

const checkChildWorkflow = `-- name: CheckChildWorkflow :one


SELECT child_workflow_id
FROM operation_outputs
WHERE workflow_uuid = $1 AND function_id = $2
`

type CheckChildWorkflowParams struct {
	WorkflowUuid string
	FunctionID   int32
}

// Queries grouped by table. The runtime sets search_path on connection so
// table names are unqualified.
//
// Methods that build SQL dynamically or rely on Postgres-specific runtime
// features stay hand-written in system_database.go for now and will be
// ported per-dialect when those features get SQLite analogues:
//
//   - listWorkflows / listSchedules: dynamic WHERE/ORDER BY assembly.
//   - dequeueWorkflows: FOR UPDATE SKIP LOCKED + per-call rate-limit/concurrency
//     branches; needs a different locking strategy in SQLite.
//   - forkWorkflow / exportWorkflow / importWorkflow: multi-statement
//     orchestration with branch-conditional SQL.
//   - deleteWorkflows / resumeWorkflows / getWorkflowChildren / cancelAllBefore /
//     awaitWorkflowResult / backfillSchedule / triggerSchedule: chain of
//     queries with control flow that doesn't fit one sqlc :query.
//
// Everything else lives below and is dialect-portable as written.
// ===== operation_outputs =====
func (q *Queries) CheckChildWorkflow(ctx context.Context, arg CheckChildWorkflowParams) (*string, error) {
	row := q.db.QueryRow(ctx, checkChildWorkflow, arg.WorkflowUuid, arg.FunctionID)
	var child_workflow_id *string
	err := row.Scan(&child_workflow_id)
	return child_workflow_id, err
}

const checkOperationOutput = `-- name: CheckOperationOutput :one
SELECT output, error, function_name, serialization
FROM operation_outputs
WHERE workflow_uuid = $1 AND function_id = $2
`

type CheckOperationOutputParams struct {
	WorkflowUuid string
	FunctionID   int32
}

type CheckOperationOutputRow struct {
	Output        *string
	Error         *string
	FunctionName  string
	Serialization *string
}

func (q *Queries) CheckOperationOutput(ctx context.Context, arg CheckOperationOutputParams) (CheckOperationOutputRow, error) {
	row := q.db.QueryRow(ctx, checkOperationOutput, arg.WorkflowUuid, arg.FunctionID)
	var i CheckOperationOutputRow
	err := row.Scan(
		&i.Output,
		&i.Error,
		&i.FunctionName,
		&i.Serialization,
	)
	return i, err
}

const clearQueueAssignment = `-- name: ClearQueueAssignment :execrows
UPDATE workflow_status
SET status = $1, started_at_epoch_ms = NULL
WHERE workflow_uuid = $2
  AND queue_name IS NOT NULL
  AND status = $3
`

type ClearQueueAssignmentParams struct {
	Status       *string
	WorkflowUuid string
	Status_2     *string
}

func (q *Queries) ClearQueueAssignment(ctx context.Context, arg ClearQueueAssignmentParams) (int64, error) {
	result, err := q.db.Exec(ctx, clearQueueAssignment, arg.Status, arg.WorkflowUuid, arg.Status_2)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const consumeOldestNotification = `-- name: ConsumeOldestNotification :one
WITH oldest_entry AS (
    SELECT n.message_uuid
    FROM notifications n
    WHERE n.destination_uuid = $1 AND n.topic = $2
    ORDER BY n.created_at_epoch_ms ASC
    LIMIT 1
)
DELETE FROM notifications
WHERE message_uuid = (SELECT message_uuid FROM oldest_entry)
RETURNING message, serialization
`

type ConsumeOldestNotificationParams struct {
	DestinationUuid string
	Topic           *string
}

type ConsumeOldestNotificationRow struct {
	Message       string
	Serialization *string
}

func (q *Queries) ConsumeOldestNotification(ctx context.Context, arg ConsumeOldestNotificationParams) (ConsumeOldestNotificationRow, error) {
	row := q.db.QueryRow(ctx, consumeOldestNotification, arg.DestinationUuid, arg.Topic)
	var i ConsumeOldestNotificationRow
	err := row.Scan(&i.Message, &i.Serialization)
	return i, err
}

const createSchedule = `-- name: CreateSchedule :exec

INSERT INTO workflow_schedules (
    schedule_id, schedule_name, workflow_name, workflow_class_name,
    schedule, context, status, automatic_backfill, cron_timezone, queue_name
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
`

type CreateScheduleParams struct {
	ScheduleID        string
	ScheduleName      string
	WorkflowName      string
	WorkflowClassName *string
	Schedule          string
	Context           string
	Status            string
	AutomaticBackfill bool
	CronTimezone      *string
	QueueName         *string
}

// ===== workflow_schedules =====
func (q *Queries) CreateSchedule(ctx context.Context, arg CreateScheduleParams) error {
	_, err := q.db.Exec(ctx, createSchedule,
		arg.ScheduleID,
		arg.ScheduleName,
		arg.WorkflowName,
		arg.WorkflowClassName,
		arg.Schedule,
		arg.Context,
		arg.Status,
		arg.AutomaticBackfill,
		arg.CronTimezone,
		arg.QueueName,
	)
	return err
}

const deleteSchedule = `-- name: DeleteSchedule :exec
DELETE FROM workflow_schedules WHERE schedule_name = $1
`

func (q *Queries) DeleteSchedule(ctx context.Context, scheduleName string) error {
	_, err := q.db.Exec(ctx, deleteSchedule, scheduleName)
	return err
}

const doesPatchExists = `-- name: DoesPatchExists :one
SELECT function_name
FROM operation_outputs
WHERE workflow_uuid = $1 AND function_id = $2
`

type DoesPatchExistsParams struct {
	WorkflowUuid string
	FunctionID   int32
}

func (q *Queries) DoesPatchExists(ctx context.Context, arg DoesPatchExistsParams) (string, error) {
	row := q.db.QueryRow(ctx, doesPatchExists, arg.WorkflowUuid, arg.FunctionID)
	var function_name string
	err := row.Scan(&function_name)
	return function_name, err
}

const garbageCollectCutoffByOffset = `-- name: GarbageCollectCutoffByOffset :one
SELECT created_at
FROM workflow_status
ORDER BY created_at DESC
LIMIT 1 OFFSET $1
`

func (q *Queries) GarbageCollectCutoffByOffset(ctx context.Context, offset int32) (int64, error) {
	row := q.db.QueryRow(ctx, garbageCollectCutoffByOffset, offset)
	var created_at int64
	err := row.Scan(&created_at)
	return created_at, err
}

const garbageCollectWorkflowsBefore = `-- name: GarbageCollectWorkflowsBefore :execrows
DELETE FROM workflow_status
WHERE created_at < $1
  AND status NOT IN ($2, $3, $4)
`

type GarbageCollectWorkflowsBeforeParams struct {
	CreatedAt int64
	Status    *string
	Status_2  *string
	Status_3  *string
}

func (q *Queries) GarbageCollectWorkflowsBefore(ctx context.Context, arg GarbageCollectWorkflowsBeforeParams) (int64, error) {
	result, err := q.db.Exec(ctx, garbageCollectWorkflowsBefore,
		arg.CreatedAt,
		arg.Status,
		arg.Status_2,
		arg.Status_3,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getMetricStepCount = `-- name: GetMetricStepCount :many
SELECT function_name, COUNT(*) AS count
FROM operation_outputs
WHERE completed_at_epoch_ms >= $1 AND completed_at_epoch_ms < $2
GROUP BY function_name
`

type GetMetricStepCountParams struct {
	CompletedAtEpochMs   *int64
	CompletedAtEpochMs_2 *int64
}

type GetMetricStepCountRow struct {
	FunctionName string
	Count        int64
}

func (q *Queries) GetMetricStepCount(ctx context.Context, arg GetMetricStepCountParams) ([]GetMetricStepCountRow, error) {
	rows, err := q.db.Query(ctx, getMetricStepCount, arg.CompletedAtEpochMs, arg.CompletedAtEpochMs_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetMetricStepCountRow
	for rows.Next() {
		var i GetMetricStepCountRow
		if err := rows.Scan(&i.FunctionName, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMetricWorkflowCount = `-- name: GetMetricWorkflowCount :many

SELECT name, COUNT(workflow_uuid) AS count
FROM workflow_status
WHERE created_at >= $1 AND created_at < $2
GROUP BY name
`

type GetMetricWorkflowCountParams struct {
	CreatedAt   int64
	CreatedAt_2 int64
}

type GetMetricWorkflowCountRow struct {
	Name  *string
	Count int64
}

// ===== metrics =====
func (q *Queries) GetMetricWorkflowCount(ctx context.Context, arg GetMetricWorkflowCountParams) ([]GetMetricWorkflowCountRow, error) {
	rows, err := q.db.Query(ctx, getMetricWorkflowCount, arg.CreatedAt, arg.CreatedAt_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetMetricWorkflowCountRow
	for rows.Next() {
		var i GetMetricWorkflowCountRow
		if err := rows.Scan(&i.Name, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getQueuePartitions = `-- name: GetQueuePartitions :many
SELECT DISTINCT queue_partition_key
FROM workflow_status
WHERE queue_name = $1
  AND status = $2
  AND queue_partition_key IS NOT NULL
`

type GetQueuePartitionsParams struct {
	QueueName *string
	Status    *string
}

func (q *Queries) GetQueuePartitions(ctx context.Context, arg GetQueuePartitionsParams) ([]*string, error) {
	rows, err := q.db.Query(ctx, getQueuePartitions, arg.QueueName, arg.Status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*string
	for rows.Next() {
		var queue_partition_key *string
		if err := rows.Scan(&queue_partition_key); err != nil {
			return nil, err
		}
		items = append(items, queue_partition_key)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getWorkflowEvent = `-- name: GetWorkflowEvent :one
SELECT value, serialization
FROM workflow_events
WHERE workflow_uuid = $1 AND key = $2
`

type GetWorkflowEventParams struct {
	WorkflowUuid string
	Key          string
}

type GetWorkflowEventRow struct {
	Value         string
	Serialization *string
}

func (q *Queries) GetWorkflowEvent(ctx context.Context, arg GetWorkflowEventParams) (GetWorkflowEventRow, error) {
	row := q.db.QueryRow(ctx, getWorkflowEvent, arg.WorkflowUuid, arg.Key)
	var i GetWorkflowEventRow
	err := row.Scan(&i.Value, &i.Serialization)
	return i, err
}

const getWorkflowStatus = `-- name: GetWorkflowStatus :one

SELECT status
FROM workflow_status
WHERE workflow_uuid = $1
`

// ===== workflow_status =====
func (q *Queries) GetWorkflowStatus(ctx context.Context, workflowUuid string) (*string, error) {
	row := q.db.QueryRow(ctx, getWorkflowStatus, workflowUuid)
	var status *string
	err := row.Scan(&status)
	return status, err
}

const getWorkflowSteps = `-- name: GetWorkflowSteps :many
SELECT function_id, function_name, output, error, child_workflow_id,
       started_at_epoch_ms, completed_at_epoch_ms, serialization
FROM operation_outputs
WHERE workflow_uuid = $1
ORDER BY function_id ASC
`

type GetWorkflowStepsRow struct {
	FunctionID         int32
	FunctionName       string
	Output             *string
	Error              *string
	ChildWorkflowID    *string
	StartedAtEpochMs   *int64
	CompletedAtEpochMs *int64
	Serialization      *string
}

func (q *Queries) GetWorkflowSteps(ctx context.Context, workflowUuid string) ([]GetWorkflowStepsRow, error) {
	rows, err := q.db.Query(ctx, getWorkflowSteps, workflowUuid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetWorkflowStepsRow
	for rows.Next() {
		var i GetWorkflowStepsRow
		if err := rows.Scan(
			&i.FunctionID,
			&i.FunctionName,
			&i.Output,
			&i.Error,
			&i.ChildWorkflowID,
			&i.StartedAtEpochMs,
			&i.CompletedAtEpochMs,
			&i.Serialization,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertNotification = `-- name: InsertNotification :exec

INSERT INTO notifications (destination_uuid, topic, message, serialization)
VALUES ($1, $2, $3, $4)
`

type InsertNotificationParams struct {
	DestinationUuid string
	Topic           *string
	Message         string
	Serialization   *string
}

// ===== notifications / events / streams =====
func (q *Queries) InsertNotification(ctx context.Context, arg InsertNotificationParams) error {
	_, err := q.db.Exec(ctx, insertNotification,
		arg.DestinationUuid,
		arg.Topic,
		arg.Message,
		arg.Serialization,
	)
	return err
}

const insertPatchMarker = `-- name: InsertPatchMarker :exec
INSERT INTO operation_outputs (workflow_uuid, function_id, function_name)
VALUES ($1, $2, $3)
`

type InsertPatchMarkerParams struct {
	WorkflowUuid string
	FunctionID   int32
	FunctionName string
}

func (q *Queries) InsertPatchMarker(ctx context.Context, arg InsertPatchMarkerParams) error {
	_, err := q.db.Exec(ctx, insertPatchMarker, arg.WorkflowUuid, arg.FunctionID, arg.FunctionName)
	return err
}

const markWorkflowDeadLetter = `-- name: MarkWorkflowDeadLetter :exec
UPDATE workflow_status
SET status = $1, deduplication_id = NULL, started_at_epoch_ms = NULL, queue_name = NULL
WHERE workflow_uuid = $2 AND status = $3
`

type MarkWorkflowDeadLetterParams struct {
	Status       *string
	WorkflowUuid string
	Status_2     *string
}

func (q *Queries) MarkWorkflowDeadLetter(ctx context.Context, arg MarkWorkflowDeadLetterParams) error {
	_, err := q.db.Exec(ctx, markWorkflowDeadLetter, arg.Status, arg.WorkflowUuid, arg.Status_2)
	return err
}

const notificationExists = `-- name: NotificationExists :one
SELECT EXISTS (
    SELECT 1 FROM notifications
    WHERE destination_uuid = $1 AND topic = $2
) AS exists
`

type NotificationExistsParams struct {
	DestinationUuid string
	Topic           *string
}

func (q *Queries) NotificationExists(ctx context.Context, arg NotificationExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, notificationExists, arg.DestinationUuid, arg.Topic)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const readStream = `-- name: ReadStream :many
SELECT value, "offset", serialization
FROM streams
WHERE workflow_uuid = $1 AND key = $2 AND "offset" >= $3
ORDER BY "offset" ASC
`

type ReadStreamParams struct {
	WorkflowUuid string
	Key          string
	Offset       int32
}

type ReadStreamRow struct {
	Value         string
	Offset        int32
	Serialization *string
}

func (q *Queries) ReadStream(ctx context.Context, arg ReadStreamParams) ([]ReadStreamRow, error) {
	rows, err := q.db.Query(ctx, readStream, arg.WorkflowUuid, arg.Key, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ReadStreamRow
	for rows.Next() {
		var i ReadStreamRow
		if err := rows.Scan(&i.Value, &i.Offset, &i.Serialization); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordChildWorkflow = `-- name: RecordChildWorkflow :exec
INSERT INTO operation_outputs (workflow_uuid, function_id, function_name, child_workflow_id)
VALUES ($1, $2, $3, $4)
`

type RecordChildWorkflowParams struct {
	WorkflowUuid    string
	FunctionID      int32
	FunctionName    string
	ChildWorkflowID *string
}

func (q *Queries) RecordChildWorkflow(ctx context.Context, arg RecordChildWorkflowParams) error {
	_, err := q.db.Exec(ctx, recordChildWorkflow,
		arg.WorkflowUuid,
		arg.FunctionID,
		arg.FunctionName,
		arg.ChildWorkflowID,
	)
	return err
}

const recordOperationResult = `-- name: RecordOperationResult :exec
INSERT INTO operation_outputs (
    workflow_uuid, function_id, output, error, function_name,
    started_at_epoch_ms, completed_at_epoch_ms, serialization, child_workflow_id
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
`

type RecordOperationResultParams struct {
	WorkflowUuid       string
	FunctionID         int32
	Output             *string
	Error              *string
	FunctionName       string
	StartedAtEpochMs   *int64
	CompletedAtEpochMs *int64
	Serialization      *string
	ChildWorkflowID    *string
}

func (q *Queries) RecordOperationResult(ctx context.Context, arg RecordOperationResultParams) error {
	_, err := q.db.Exec(ctx, recordOperationResult,
		arg.WorkflowUuid,
		arg.FunctionID,
		arg.Output,
		arg.Error,
		arg.FunctionName,
		arg.StartedAtEpochMs,
		arg.CompletedAtEpochMs,
		arg.Serialization,
		arg.ChildWorkflowID,
	)
	return err
}

const setWorkflowDelay = `-- name: SetWorkflowDelay :exec
UPDATE workflow_status
SET delay_until_epoch_ms = $1, updated_at = $2
WHERE workflow_uuid = $3
  AND status = $4
`

type SetWorkflowDelayParams struct {
	DelayUntilEpochMs *int64
	UpdatedAt         int64
	WorkflowUuid      string
	Status            *string
}

func (q *Queries) SetWorkflowDelay(ctx context.Context, arg SetWorkflowDelayParams) error {
	_, err := q.db.Exec(ctx, setWorkflowDelay,
		arg.DelayUntilEpochMs,
		arg.UpdatedAt,
		arg.WorkflowUuid,
		arg.Status,
	)
	return err
}

const streamIsClosed = `-- name: StreamIsClosed :one
SELECT 1 AS one
FROM streams
WHERE workflow_uuid = $1 AND key = $2 AND value = $3
LIMIT 1
`

type StreamIsClosedParams struct {
	WorkflowUuid string
	Key          string
	Value        string
}

func (q *Queries) StreamIsClosed(ctx context.Context, arg StreamIsClosedParams) (int32, error) {
	row := q.db.QueryRow(ctx, streamIsClosed, arg.WorkflowUuid, arg.Key, arg.Value)
	var one int32
	err := row.Scan(&one)
	return one, err
}

const transitionDelayedWorkflows = `-- name: TransitionDelayedWorkflows :exec
UPDATE workflow_status
SET status = $1
WHERE status = $2
  AND delay_until_epoch_ms <= $3
`

type TransitionDelayedWorkflowsParams struct {
	Status            *string
	Status_2          *string
	DelayUntilEpochMs *int64
}

func (q *Queries) TransitionDelayedWorkflows(ctx context.Context, arg TransitionDelayedWorkflowsParams) error {
	_, err := q.db.Exec(ctx, transitionDelayedWorkflows, arg.Status, arg.Status_2, arg.DelayUntilEpochMs)
	return err
}

const updateSchedule = `-- name: UpdateSchedule :exec
UPDATE workflow_schedules
SET status = $1, last_fired_at = $2
WHERE schedule_name = $3
`

type UpdateScheduleParams struct {
	Status       string
	LastFiredAt  *string
	ScheduleName string
}

func (q *Queries) UpdateSchedule(ctx context.Context, arg UpdateScheduleParams) error {
	_, err := q.db.Exec(ctx, updateSchedule, arg.Status, arg.LastFiredAt, arg.ScheduleName)
	return err
}

const updateScheduleLastFiredAt = `-- name: UpdateScheduleLastFiredAt :exec
UPDATE workflow_schedules
SET last_fired_at = $1
WHERE schedule_name = $2
`

type UpdateScheduleLastFiredAtParams struct {
	LastFiredAt  *string
	ScheduleName string
}

func (q *Queries) UpdateScheduleLastFiredAt(ctx context.Context, arg UpdateScheduleLastFiredAtParams) error {
	_, err := q.db.Exec(ctx, updateScheduleLastFiredAt, arg.LastFiredAt, arg.ScheduleName)
	return err
}

const updateWorkflowOutcome = `-- name: UpdateWorkflowOutcome :exec
UPDATE workflow_status
SET status = $1, output = $2, error = $3, updated_at = $4, deduplication_id = NULL
WHERE workflow_uuid = $5 AND NOT (status = $6 AND $1::TEXT IN ($7, $8))
`

type UpdateWorkflowOutcomeParams struct {
	Status       *string
	Output       *string
	Error        *string
	UpdatedAt    int64
	WorkflowUuid string
	Status_2     *string
	Column7      interface{}
	Column8      interface{}
}

func (q *Queries) UpdateWorkflowOutcome(ctx context.Context, arg UpdateWorkflowOutcomeParams) error {
	_, err := q.db.Exec(ctx, updateWorkflowOutcome,
		arg.Status,
		arg.Output,
		arg.Error,
		arg.UpdatedAt,
		arg.WorkflowUuid,
		arg.Status_2,
		arg.Column7,
		arg.Column8,
	)
	return err
}

const updateWorkflowToCancelled = `-- name: UpdateWorkflowToCancelled :exec
UPDATE workflow_status
SET status = $1, updated_at = $2, started_at_epoch_ms = NULL,
    queue_name = NULL, deduplication_id = NULL
WHERE workflow_uuid = $3
`

type UpdateWorkflowToCancelledParams struct {
	Status       *string
	UpdatedAt    int64
	WorkflowUuid string
}

func (q *Queries) UpdateWorkflowToCancelled(ctx context.Context, arg UpdateWorkflowToCancelledParams) error {
	_, err := q.db.Exec(ctx, updateWorkflowToCancelled, arg.Status, arg.UpdatedAt, arg.WorkflowUuid)
	return err
}

const upsertWorkflowEvent = `-- name: UpsertWorkflowEvent :exec
INSERT INTO workflow_events (workflow_uuid, key, value, serialization)
VALUES ($1, $2, $3, $4)
ON CONFLICT (workflow_uuid, key)
DO UPDATE SET value = EXCLUDED.value, serialization = EXCLUDED.serialization
`

type UpsertWorkflowEventParams struct {
	WorkflowUuid  string
	Key           string
	Value         string
	Serialization *string
}

func (q *Queries) UpsertWorkflowEvent(ctx context.Context, arg UpsertWorkflowEventParams) error {
	_, err := q.db.Exec(ctx, upsertWorkflowEvent,
		arg.WorkflowUuid,
		arg.Key,
		arg.Value,
		arg.Serialization,
	)
	return err
}

const upsertWorkflowEventHistory = `-- name: UpsertWorkflowEventHistory :exec
INSERT INTO workflow_events_history (workflow_uuid, function_id, key, value, serialization)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (workflow_uuid, function_id, key)
DO UPDATE SET value = EXCLUDED.value, serialization = EXCLUDED.serialization
`

type UpsertWorkflowEventHistoryParams struct {
	WorkflowUuid  string
	FunctionID    int32
	Key           string
	Value         string
	Serialization *string
}

func (q *Queries) UpsertWorkflowEventHistory(ctx context.Context, arg UpsertWorkflowEventHistoryParams) error {
	_, err := q.db.Exec(ctx, upsertWorkflowEventHistory,
		arg.WorkflowUuid,
		arg.FunctionID,
		arg.Key,
		arg.Value,
		arg.Serialization,
	)
	return err
}

const workflowExists = `-- name: WorkflowExists :one
SELECT 1 AS one
FROM workflow_status
WHERE workflow_uuid = $1
LIMIT 1
`

func (q *Queries) WorkflowExists(ctx context.Context, workflowUuid string) (int32, error) {
	row := q.db.QueryRow(ctx, workflowExists, workflowUuid)
	var one int32
	err := row.Scan(&one)
	return one, err
}
