// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package sqlcgen

import (
	"context"
)

const checkChildWorkflow = `-- name: CheckChildWorkflow :one
SELECT child_workflow_id
FROM operation_outputs
WHERE workflow_uuid = $1 AND function_id = $2
`

type CheckChildWorkflowParams struct {
	WorkflowUuid string
	FunctionID   int32
}

func (q *Queries) CheckChildWorkflow(ctx context.Context, arg CheckChildWorkflowParams) (*string, error) {
	row := q.db.QueryRow(ctx, checkChildWorkflow, arg.WorkflowUuid, arg.FunctionID)
	var child_workflow_id *string
	err := row.Scan(&child_workflow_id)
	return child_workflow_id, err
}

const getWorkflowStatus = `-- name: GetWorkflowStatus :one
SELECT status
FROM workflow_status
WHERE workflow_uuid = $1
`

func (q *Queries) GetWorkflowStatus(ctx context.Context, workflowUuid string) (*string, error) {
	row := q.db.QueryRow(ctx, getWorkflowStatus, workflowUuid)
	var status *string
	err := row.Scan(&status)
	return status, err
}
